name: CI - SAST - SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  sast-pr:
    name: SonarQube SAST Scan (PR Feedback)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build Java project
        run: mvn clean compile

      - name: SonarQube Scan (PR - no gate enforcement)
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=pdotnext_sonarqube-sast-lab
            -Dsonar.organization=pdotnext
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.java.binaries=target/classes
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.qualitygate.wait=false

# --------------------------------------------------------------------------------

  # MAIN BRANCH - QUALITY GATE ENFORCE

# --------------------------------------------------------------------------------

  sast-main:
    name: SonarQube SAST Scan (Main -Enforce Quality Gate)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java project
        run: mvn clean compile

      - name: SonarQube Scan (Main -Enforce Quality Gate)
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=pdotnext_sonarqube-sast-lab
            -Dsonar.organization=pdotnext
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.java.binaries=target/classes
            -Dsonar.qualitygate.wait=true